authorName: john kim
experimentName: ner
trialConcurrency: 8
#maxExecDuration: 24h
#maxTrialNum: 10
trainingServicePlatform: local
searchSpacePath: search_space-3.json
useAnnotation: false
tuner:
  builtinTunerName: SMAC
  classArgs:
    optimize_mode: maximize
trial:
  command: python3 train.py --conf conf/nni3.yaml --do_nni true
  codeDir: ..
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu: 2
  useActiveGpu: true
